import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { Parallax } from 'react-scroll-parallax'
import Sound from 'react-sound'
import { Component } from 'react/cjs/react.production.min'
import { useState } from 'react'

export default class Home extends Component {
  constructor(props) {
    super(props);
    this.state = {
      isPLaying: false
    };
  }

  render() {
    return <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.Main} onClick={() => this.setState({ isPLaying: true })}>
        {this.state.isPLaying ? <Sound
          url="Hedwigs Flight.mp3"
          playStatus={Sound.status.PLAYING}
          playFromPosition={300 /* in milliseconds */}
          onLoading={this.handleSongLoading}
          onPlaying={this.handleSongPlaying}
          onFinishedPlaying={this.handleSongFinishedPlaying}
          volume={40}
        /> : ""}
        <div className={styles.Scene}>
          <div className={styles.Layer}>
            <Parallax speed={-70} style={{width: '100%',height: '100%'}}>
              <div className={styles.ImageWarpper}>
                <Image src={"/hogwards/V9.png"} alt="" layout="fill" objectFit="cover" />
              </div>
            </Parallax>
          </div>
          {/* <div className={styles.Layer}>
            <Parallax speed={-65} style={{width: '100%',height: '100%'}}>
              <div className={styles.ImageWarpper}>
                <Image src={"/hogwards/V8.png"} alt="" layout="fill" objectFit="cover" />
              </div>
            </Parallax>
          </div> */}
          <div className={styles.Layer}>
            <Parallax speed={-60} style={{width: '100%',height: '100%'}}>
              <div className={styles.ImageWarpper}>
                <Image src={"/hogwards/V7.png"} alt="" layout="fill" objectFit="cover" />
              </div>
            </Parallax>
          </div>
          <div className={styles.Layer}>
            <Parallax speed={-55} style={{width: '100%',height: '100%'}}>
              <div className={styles.ImageWarpper}>
                <Image src={"/hogwards/V6.png"} alt="" layout="fill" objectFit="cover" />
              </div>
            </Parallax>
          </div>
          <div className={styles.Layer}>
            <Parallax speed={-50} style={{width: '100%',height: '100%'}}>
              <div className={styles.ImageWarpper}>
                <Image src={"/hogwards/V5.png"} alt="" layout="fill" objectFit="cover" />
              </div>
            </Parallax>
          </div>
          <div className={styles.Layer}>
            <Parallax speed={-45} style={{width: '100%',height: '100%'}}>
              <div className={styles.ImageWarpper}>
                <Image src={"/hogwards/V4.png"} alt="" layout="fill" objectFit="cover" />
              </div>
            </Parallax>
          </div>
          <div style={{filter: "blur(2px)"}} className={styles.Layer}>
            <Parallax speed={-30} style={{width: '100%',height: '100%'}}>
              <div className={styles.ImageWarpper}>
                <Image src={"/hogwards/V3.png"} alt="" layout="fill" objectFit="cover" />
              </div>
            </Parallax>
          </div>
          <div style={{filter: "blur(5px)"}} className={styles.Layer}>
            <Parallax speed={-20} style={{width: '100%',height: '100%'}}>
              <div className={styles.ImageWarpper}>
                <Image src={"/hogwards/V2.png"} alt="" layout="fill" objectFit="cover" />
              </div>
            </Parallax>
          </div>
          <div style={{filter: "blur(10px)"}} className={styles.Layer}>
            <Parallax speed={0} style={{width: '100%',height: '100%'}}>
              <div className={styles.ImageWarpper}>
                <Image src={"/hogwards/V1.png"} alt="" layout="fill" objectFit="cover" />
              </div>
            </Parallax>
          </div>
        </div>
        <div className={styles.Green}>
          <div className={styles.TextContainer}>
            <h1 className={styles.Title}>
              {"HOGWARTS LETTER."}
            </h1>
            <p className={styles.Text}>I asked again but my hope refused to extinguish,<br/>
              It smiled and told I had always been distinguished.<br/>
              So, I kept checking my mail box even if it seemed lame,<br/>
              I kept waiting and waiting but that Hogwarts letter never came.<br/>
              <br/>
              Eleven progressed to twelve, twelve to thirteen,<br/>
              Mistaken- I thought-they must have been,<br/>
              Meanwhile I did my own reading and learnt all the curses,<br/>
              And with the wand I never had I practiced all the verses.<br/>
              <br/>
              First of September arrived again, and again, and again.<br/>
              And with the years that passed, so increased the pain,<br/>
              “So the age limit isn’t actually eleven!” then I optimistically thought,<br/>
              “Oh! What a brutal test of patience they cleverly plot!”<br/>
              <br/>
              Pictures in newspaper don’t move, brooms yet don’t fly,<br/>
              And yes there are times that these thoughts make me cry,<br/>
              “Hogwarts doesn’t exist”- Oh! These oblivious muggles continue to tell,<br/>
              Deep down they are just jealous that they just can’t cast a spell,<br/>
              “Well, can you?” they ask laughing and teasing,<br/>
              Their voice brimming up with sarcastic appeasing…<br/>
              “Not yet” I silently speak, “Just wait for days some...<br/>
              My pretty little Hogwarts letter is just about to come.”<br/>
            </p>
          </div>
        </div>
      </main>
    </div>
  }
}

